set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim

set nu
syntax on
set noswapfile 
set noundofile  
set nobackup
set nowritebackup
set lbr!
set ignorecase
set incsearch

highlight Normal guibg=black guifg=white
highlight comment ctermfg=lightblue
syntax enable

" status bar
set laststatus=0
set shiftwidth=4

" tab spaces = 4
set ts=4

" remove the toolbar from gvim
set guioptions-=T

" Set font for gvim in windws
set guifont=Lucida\ Console:h8

" My Maps
" Tabs
nmap te :tabedit
nmap tc :tabclose<CR>
nmap tn :tabnext<CR>
nmap tp :tabprevious<CR>
nmap tf :tabfirst<CR>
nmap tl :tablast<CR>

behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

