export BASH_SILENCE_DEPRECATION_WARNING=1

# start/stop apache and mysql for local wordpress development
alias wp-start="sudo apachectl start && mysql.server start"
alias wp-stop="sudo apachectl stop && mysql.server stop"

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
export PATH="/usr/local/opt/ruby/bin:$PATH"

# export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
#alias ls='ls -GFh'
